---
- name: Install & Start nginx web server
  hosts: apt_hosts
  become: yes
  tasks:
  - name: Install nginx server
    apt:
      name: nginx
      state: present
  - name: Start nginx server
    service:
      name: nginx
      state: started
    
